name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'

    - name: Install dependencies
      run: yarn

    - name: Build the source
      run: yarn build

    - name: Run unit tests
      run: yarn test --junit --outputFile=test-results/junit.xml
      env:
        CI: true # Ensures test results are formatted for CI environments

    - name: Run E2E tests
      run: yarn test:e2e --junit --outputFile=test-results/e2e-junit.xml
      env:
        CI: true

    - name: Upload JUnit test results
      uses: actions/upload-artifact@v3
      with:
        name: junit-test-results
        path: test-results/*.xml

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      with:
        name: JUnit Tests
        path: test-results/*.xml
        reporter: junit
