# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Do yarn stuff
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
    - run: yarn
    - run: yarn build
    - run: yarn test
    - run: yarn test:e2e

    - uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: reports/jest-*.xml    # Path to test results
        reporter: jest-junit        # Format of test results
